### ISSUE TITLE
RootObject.add_unique timing

### ISSUE THREAD

**Issue by stwunsch** [KIT-CMS/shape-producer#11]
Hi!
Folgendes Problem: Ich hab den shape_producer fuer die SM analyse geprofiled und wir verwenden die meiste Zeit auf `RootObject.add_unique`. Das Problem ist die explodierende Kombinatorik bei vielen Systematiken (was wir haben).

@ArturAkh Koennen wir das nicht einfach entfernen? Es ist wesentlich billiger manche shapes doppelt zu produzieren als die jetzige Implementierung.

**Comment by ArturAkh** [comment]
Hi Stefan,

Gerne! Was ich beobachtet habe, ist, dass die doppelten shapes ab und zu leicht unterschiedliche Integralle haben. Aber da das nur numerische Schwankungen sind, sollte das irrelevant sein.

Viele Grüße,

Artur

**Comment by stwunsch** [comment]
Ich haette da auch keine numerischen Schwankungen erwartet! Wie gross sind die unterschiede?

**Comment by ArturAkh** [comment]
Soweit ich weiß, weniger als %-Level, aber das ist schon ein Weilchen her, dass ich die Sachen mir angeschaut habe.
